import { test, expect } from "@playwright/test";
import { pdfFixture } from "./fixtures";
import { randomUUID } from "node:crypto";

test("anonymous public browsing and administrative authorization boundary",async({page,request})=>{
  await page.goto("/boards/");await expect(page.locator(".board-card")).toHaveCount(3);
  await page.goto("/admin/boards/");await expect(page).toHaveURL(/\/admin\/login/);
  for(const url of ["/api/admin/boards/","/api/admin/boards/unknown/"]) expect((await request.get(url)).status()).toBe(401);
  expect((await request.post("/api/admin/boards/",{headers:{Origin:"http://localhost:4173"},data:{}})).status()).toBe(401);
  expect((await request.post("/api/admin/login/",{headers:{Origin:"https://wrong.example"},data:{username:"x",password:"x"}})).status()).toBe(403);
  expect((await request.delete("/api/admin/boards/unknown/",{headers:{Origin:"http://localhost:4173"},data:{version:1,confirmation:"X"}})).status()).toBe(401);
  expect((await request.post("/api/admin/signup/",{data:{}})).status()).toBe(404);
});

test("three-section uploads, PDF previews, primary cover, private edits and individual removal",async({page,browser},testInfo)=>{
  const id=`ASSETS-${randomUUID().slice(0,8)}`;const slug=id.toLowerCase();
  const visitor=await browser.newContext({viewport:page.viewportSize()!});const publicPage=await visitor.newPage();
  await page.goto("/admin/login/");
  await page.getByLabel("Username",{exact:true}).fill("browser-test-admin");
  await page.getByLabel("Password",{exact:true}).fill("Browser-test-password-2026");
  await page.getByRole("button",{name:"Sign in",exact:true}).click();
  await expect(page).toHaveURL(/\/admin\/boards/);
  await page.goto("/admin/boards/new/");
  for(const name of ["Schematic","3D Render","Physical Board"]) await expect(page.getByRole("heading",{name,exact:true})).toBeVisible();
  await expect(page.locator('input[type="file"]')).toHaveCount(3);
  await expect(page.getByText(/SchDoc|PcbDoc|GLB|GLTF|Gerber|Altium/)).toHaveCount(0);
  await page.getByLabel("PCB ID",{exact:true}).fill(id);
  await page.getByLabel("URL slug",{exact:true}).fill(slug);
  await page.getByLabel("PCB name",{exact:true}).fill("Media workflow test");
  await page.getByLabel("Description",{exact:true}).fill("Fixture only; no engineering data.");
  const image=Buffer.from("iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+/l9sAAAAASUVORK5CYII=","base64");
  await page.getByLabel("Schematic PDF",{exact:true}).setInputFiles({name:"schematic.pdf",mimeType:"application/pdf",buffer:pdfFixture()});
  await page.getByLabel("3D Render files",{exact:true}).setInputFiles([{name:"render.png",mimeType:"image/png",buffer:image},{name:"assembly.pdf",mimeType:"application/pdf",buffer:pdfFixture()}]);
  await page.getByLabel("Physical Board files",{exact:true}).setInputFiles([{name:"assembled.png",mimeType:"image/png",buffer:image},{name:"physical.pdf",mimeType:"application/pdf",buffer:pdfFixture()}]);
  await page.getByLabel("Caption for physical.pdf",{exact:true}).fill("Assembly documentation");
  let failed=false;
  await page.route("**/api/admin/boards/*/upload",async route=>{
    if(!failed && route.request().postDataBuffer()?.includes(Buffer.from("physical.pdf"))) {failed=true;await route.fulfill({status:500,contentType:"application/json",body:JSON.stringify({error:"Upload interrupted; retry."})});}
    else await route.continue();
  });
  await page.getByRole("button",{name:"Publish",exact:true}).click();
  await expect(page.locator("main").getByRole("alert")).toContainText("Upload interrupted");
  await expect(page.getByRole("link",{name:"assembly.pdf",exact:true})).toBeVisible();
  const key=page.url().match(/boards\/([^/]+)\/edit/)![1];
  expect((await visitor.request.get(`/boards/${slug}/`)).status()).toBe(404);
  await expect(page.getByLabel("Caption for physical.pdf",{exact:true})).toHaveValue("Assembly documentation");
  await page.getByRole("button",{name:"Save Draft",exact:true}).click();
  await expect(page.getByRole("status")).toContainText("Draft saved");
  const draft=await page.evaluate(async key=>await(await fetch(`/api/admin/boards/${key}/`)).json(),key);
  expect(draft.assets.filter((a:{name:string})=>a.name==="schematic.pdf")).toHaveLength(1);
  const unsupported=await page.request.post(`/api/admin/boards/${key}/upload/`,{headers:{Origin:"http://localhost:4173"},multipart:{version:String(draft.record.version),role:"source",files:{name:"legacy.SchDoc",mimeType:"application/octet-stream",buffer:Buffer.from("d0cf11e0a1b11ae1","hex")}}});
  expect(unsupported.status()).toBe(400);
  const pdfUrl=draft.record.board.model3d.renders[1];
  const photoUrl=draft.record.board.photos[0].src;
  expect((await visitor.request.get(pdfUrl)).status()).toBe(404);
  await page.locator(".admin-upload-file").filter({has:page.getByRole("link",{name:"assembly.pdf",exact:true})}).getByLabel("Primary cover",{exact:true}).check();
  await page.getByRole("button",{name:"Publish",exact:true}).click();
  await expect(page.getByRole("status")).toContainText("Published.");
  await publicPage.goto(`/boards/${slug}/`);
  await expect(publicPage.locator("#layout")).toHaveCount(0);
  for(const section of ["schematic","model","photos"]) await expect(publicPage.locator(`#${section} .pdf-preview`)).toHaveCount(1);
  await expect(publicPage.locator("#model .pdf-pages")).toHaveAttribute("data-pdf-src",pdfUrl);
  const schematic=publicPage.locator("#schematic");
  await schematic.scrollIntoViewIfNeeded();
  await expect(schematic.locator("canvas")).toHaveCount(2);
  await expect(schematic.locator("canvas").first()).toHaveAttribute("data-rendered","true");
  await schematic.getByRole("button",{name:"Enlarge PDF"}).click();
  const dialog=publicPage.getByRole("dialog",{name:"Schematic PDF",exact:true});
  await expect(dialog).toBeVisible();
  await dialog.getByRole("combobox",{name:"Zoom",exact:true}).selectOption("1.5");
  await expect(dialog.locator("canvas")).toHaveCount(2);
  await dialog.locator("canvas").last().scrollIntoViewIfNeeded();
  await expect(dialog.locator("canvas").last()).toHaveAttribute("data-rendered","true");
  expect(await dialog.locator("canvas").evaluateAll(canvases=>canvases[1].getBoundingClientRect().top >= canvases[0].getBoundingClientRect().bottom)).toBe(true);
  expect(await dialog.locator(".pdf-toolbar").evaluate(toolbar=>toolbar.getBoundingClientRect().top>=0)).toBe(true);
  await publicPage.screenshot({path:testInfo.outputPath("pdf-dialog.png")});
  await publicPage.keyboard.press("Escape");
  await expect(dialog).not.toBeVisible();
  const response=await visitor.request.get(pdfUrl,{headers:{Range:"bytes=0-4"}});
  expect(response.status()).toBe(206);expect(await response.text()).toBe("%PDF-");
  expect(response.headers()["content-disposition"]).toContain("inline");
  await publicPage.route(`**${pdfUrl}`,route=>route.fulfill({status:503,body:"Unavailable"}));
  await publicPage.reload();await publicPage.locator("#model .pdf-pages").scrollIntoViewIfNeeded();
  await expect(publicPage.locator("#model .pdf-pages")).toContainText("PDF preview unavailable");
  await expect(publicPage.locator("#model").getByRole("link",{name:"Open PDF",exact:true})).toHaveAttribute("href",pdfUrl);
  await publicPage.unroute(`**${pdfUrl}`);
  await publicPage.goto(`/boards/?q=${id}`);
  await expect(publicPage.locator(".board-card .pdf-thumbnail")).toHaveAttribute("data-pdf-src",pdfUrl);
  await publicPage.locator(".board-card").scrollIntoViewIfNeeded();
  await expect(publicPage.locator(".board-card canvas")).toHaveCount(1);
  await publicPage.screenshot({path:testInfo.outputPath("pdf-cover.png"),fullPage:true});
  await page.getByLabel("PCB name",{exact:true}).fill("Private updated title");
  await page.locator(".admin-upload-file").filter({has:page.getByRole("link",{name:"assembled.png",exact:true})}).getByRole("button",{name:"Remove from draft"}).click();
  await page.getByRole("button",{name:"Save Draft",exact:true}).click();
  await expect(page.getByRole("status")).toContainText("Draft saved");
  expect((await visitor.request.get(photoUrl)).status()).toBe(200);
  await publicPage.reload();await expect(publicPage.locator(".board-card")).toContainText("Media workflow test");
  await page.getByRole("button",{name:"Publish",exact:true}).click();
  await expect(page.getByRole("status")).toContainText("Published.");
  expect((await visitor.request.get(photoUrl)).status()).toBe(404);
  await page.getByRole("button",{name:"Archive",exact:true}).click();
  await expect(page.getByRole("status")).toContainText("Archived.");
  expect((await visitor.request.get(pdfUrl)).status()).toBe(404);
  await page.getByRole("button",{name:"Restore as Draft",exact:true}).click();
  await expect(page.getByRole("status")).toContainText("Restored as a private draft");
  await page.getByRole("button",{name:"Publish",exact:true}).click();
  await expect(page.getByRole("status")).toContainText("Published.");
  await page.goto("/admin/boards/");
  const row=page.getByRole("row").filter({hasText:id});await row.getByRole("button",{name:"Delete",exact:true}).click();
  const confirmation=page.getByRole("dialog",{name:`Delete PCB ${id}`});
  await expect(confirmation.getByRole("button",{name:"Delete permanently"})).toBeDisabled();
  await confirmation.getByLabel(`Type ${id} to confirm`).fill(id);
  await confirmation.getByRole("button",{name:"Delete permanently"}).click();
  await expect(row).toHaveCount(0);
  expect((await visitor.request.get(pdfUrl)).status()).toBe(404);
  await visitor.close();
});
